### ISSUE TITLE
TASK: Create an `epic` issue template

### ISSUE THREAD

**Issue by billydaly-qbiz** [Qbizinc/python-boilerplate#1]
## Summary

Create an `epic` issue template that can be used to create an issue for an epic

## To Do

- [ ] Create `ISSUE_TEMPLATE/epic.md` with the following sections
  - [ ] User Story
  - [ ] Goals
  - [ ] Non-goals
  - [ ] Related Tasks
- [ ] Add the following metadata to the front-matter:
  - [ ] **Name:** epic
  - [ ] **Title:** EPIC:
  - [ ] **Description:** Describe a high-level initiative or milestone that encompasses multiple tasks. 
  - [ ] **Labels:** epic

## Definition of Done

- [ ] Users and contributors are presented with an issue option called "Epic" when creating a new issue
