### ISSUE TITLE
EPIC: Making it easier to reuse this template for a new project

### ISSUE THREAD

**Issue by billydaly-qbiz** [Qbizinc/python-boilerplate#8]
## User Story

As a {type of user, e.g. developer, client, etc.}, I want to {goal or action the user wants to complete}, so that {motivation for completing the action}

## Goals

This epic will be successful if the following items are accomplished.

- [ ] {Description of change 1}
- [ ] {Description of change 2}

## Non-Goals

The following items are explicitly excluded from the scope of this epic.

- [ ] {Item excluded from scope of this epic}
- [ ] {Item excluded from scope of this epic}

## Related Tasks and Features

- #2 
- {Task 2}
